FROM node:10-alpine

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR '/app'

# Copy package.json and package-lock.json separately to leverage caching
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

ENV API_URL=https://api.randomuser.me/

EXPOSE 3000

# Define the command to start the application
CMD ["npm", "start"]
